name: Deploy to AWS

on:
  push:
    branches:
      - main  # Se activará cuando hagas push a la rama 'main'

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar credenciales AWS para Terraform
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      # Instalar dependencias de Python en un directorio específico
      - name: Install Python dependencies
        run: |
          pip install -r lambda/requirements.txt -t ./lambda_package
          cp lambda/lambda_function.py ./lambda_package/

      # Crear un archivo ZIP que incluya las dependencias y el código Lambda
      - name: Zip Lambda Function
        run: |
          cd lambda_package
          zip -r ../lambda_function.zip .

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Destroy Lambda Function
        run: terraform destroy -target=aws_lambda_function.tutur_lambda -auto-approve

      - name: Terraform Apply
        run: terraform apply -auto-approve

  deploy_lambda:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar credenciales AWS para el despliegue de Lambda
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Subir el archivo ZIP completo (código + dependencias) a S3
      - name: Upload Lambda to S3
        run: aws s3 cp lambda_function.zip s3://0002-tutur-resources

      # Desplegar la nueva versión de la Lambda desde S3
      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name TuturRAGLambda \
            --s3-bucket 0002-tutur-resources \
            --s3-key lambda_function.zip
